package main

var InitialMap = [Rows][Cols]int{
	{CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall },
	{CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellWall },
	{CellWall , CellDot  , CellWall , CellWall , CellDot  , CellWall , CellWall , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellWall , CellWall , CellDot  , CellWall , CellWall , CellDot  , CellWall },
	{CellWall , CellDot  , CellWall , CellWall , CellDot  , CellWall , CellWall , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellWall , CellWall , CellDot  , CellWall , CellWall , CellDot  , CellWall },
	{CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellWall },
	{CellWall , CellDot  , CellWall , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellWall , CellWall , CellWall , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellWall , CellDot  , CellWall },
	{CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellWall },
	{CellWall , CellWall , CellWall , CellWall , CellDot  , CellWall , CellWall , CellWall , CellEmpty, CellWall , CellEmpty, CellWall , CellWall , CellWall , CellDot  , CellWall , CellWall , CellWall , CellWall },
	{CellEmpty, CellEmpty, CellEmpty, CellWall , CellDot  , CellWall , CellEmpty, CellEmpty, CellEmpty, CellEmpty, CellEmpty, CellEmpty, CellEmpty, CellWall , CellDot  , CellWall , CellEmpty, CellEmpty, CellEmpty},
	{CellWall , CellWall , CellWall , CellWall , CellDot  , CellWall , CellEmpty, CellWall , CellWall , CellGate , CellWall , CellWall , CellEmpty, CellWall , CellDot  , CellWall , CellWall , CellWall , CellWall },
	{CellEmpty, CellDot  , CellDot  , CellDot  , CellDot  , CellEmpty, CellEmpty, CellWall , CellEmpty, CellEmpty, CellEmpty, CellWall , CellEmpty, CellEmpty, CellDot  , CellDot  , CellDot  , CellDot  , CellEmpty},
	{CellWall , CellWall , CellWall , CellWall , CellDot  , CellWall , CellEmpty, CellWall , CellWall , CellWall , CellWall , CellWall , CellEmpty, CellWall , CellDot  , CellWall , CellWall , CellWall , CellWall },
	{CellEmpty, CellEmpty, CellEmpty, CellWall , CellDot  , CellWall , CellEmpty, CellEmpty, CellEmpty, CellEmpty, CellEmpty, CellEmpty, CellEmpty, CellWall , CellDot  , CellWall , CellEmpty, CellEmpty, CellEmpty},
	{CellWall , CellWall , CellWall , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellWall , CellWall , CellWall , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellWall , CellWall , CellWall },
	{CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellWall },
	{CellWall , CellDot  , CellWall , CellWall , CellDot  , CellWall , CellWall , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellWall , CellWall , CellDot  , CellWall , CellWall , CellDot  , CellWall },
	{CellWall , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellEmpty, CellDot  , CellDot  , CellDot  , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellWall },
	{CellWall , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellWall , CellWall , CellWall , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellDot  , CellWall , CellWall },
	{CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellDot  , CellWall , CellDot  , CellDot  , CellDot  , CellDot  , CellWall },
	{CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall },
	{CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall , CellWall },
}
